baseurl: ""  # Keep it empty
url: "https://shammari.github.io"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

relative_links:
  enabled: true
  collections: true

title: "Dr. Abdullah Al-Shammari"
description: "Mathematical modeling, dynamical systems, and interdisciplinary research"
logo: "/_assets/images/profile.jpg"
show_downloads: false

include:
  - README.md
