remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

title: "Dr. Abdullah Al-Shammari"
description: "Mathematical modeling, dynamical systems, and interdisciplinary research"
logo: "/assets/images/profile.png"
show_downloads: false
